// @flow

const THROW_DICE_END = 'THROW_DICE_END';
const THROW_DICE_START = 'THROW_DICE_START';
const RESET_DICE = 'RESET_DICE';

const ADD_REMOVE_PIECES = 'ADD_REMOVE_PIECES';
const ADD_ALL_PIECES = 'ADD_ALL_PIECES';

const TOGGLE_PLAYERS_TURN = 'TOGGLE_PLAYERS_TURN';
const PLAYER_GETS_TOKEN_HOME = 'PLAYER_GETS_TOKEN_HOME';
const PLAYER_HAS_TOKEN_RESET = 'PLAYER_HAS_TOKEN_RESET';

const UPDATE_PIECE = 'UPDATE_PIECE';

const GAME_START = 'GAME_START';
const GAME_END = 'GAME_END';

const LANDED_ON_ROSETTE = 'LANDED_ON_ROSETTE';
const END_OF_TURN = 'END_OF_TURN';
const START_OF_TURN = 'START_OF_TURN';

export {
  THROW_DICE_END,
  THROW_DICE_START,
  RESET_DICE,
  ADD_REMOVE_PIECES,
  ADD_ALL_PIECES,
  TOGGLE_PLAYERS_TURN,
  PLAYER_GETS_TOKEN_HOME,
  PLAYER_HAS_TOKEN_RESET,
  UPDATE_PIECE,
  GAME_START,
  GAME_END,
  LANDED_ON_ROSETTE,
  END_OF_TURN,
  START_OF_TURN,
};

