// @flow

const THROW_DICE_END = 'THROW_DICE_END';
const THROW_DICE_START = 'THROW_DICE_START';
const RESET_DICE = 'RESET_DICE';

const ADD_REMOVE_COUNTERS = 'ADD_REMOVE_COUNTERS';
const ADD_ALL_COUNTERS = 'ADD_ALL_COUNTERS';

const TOGGLE_PLAYERS_TURN = 'TOGGLE_PLAYERS_TURN';
const PLAYER_GETS_TOKEN_HOME = 'PLAYER_GETS_TOKEN_HOME';
const PLAYER_HAS_TOKEN_RESET = 'PLAYER_HAS_TOKEN_RESET';

const UPDATE_COUNTER = 'UPDATE_COUNTER';
const CAN_CLICK_ON_COUNTER = 'CAN_CLICK_ON_COUNTER';
const CLICKED_ON_COUNTER_ATTEMPT = 'CLICKED_ON_COUNTER_ATTEMPT';
const CLICKED_ON_COUNTER_SUCCESS = 'CLICKED_ON_COUNTER_SUCCESS';
const CLICKED_ON_COUNTER_FAILURE = 'CLICKED_ON_COUNTER';
const HOVERED_ON_COUNTER = 'HOVERED_ON_COUNTER';
const COUNTER_MOVE_ATTEMPT = 'COUNTER_MOVE_ATTEMPT';
const COUNTER_MOVE_SUCCESS = 'COUNTER_MOVE_SUCCESS';
const COUNTER_MOVE_FAILURE = 'COUNTER_MOVE_FAILURE';

const GAME_START = 'GAME_START';
const GAME_END = 'GAME_END';
const SHOW_GAME_MESSAGE = 'SHOW_MESSAGE';
const HIDE_GAME_MESSAGE = 'HIDE_GAME_MESSAGE';

const LANDED_ON_ROSETTE = 'LANDED_ON_ROSETTE';
const END_OF_TURN = 'END_OF_TURN';
const START_OF_TURN = 'START_OF_TURN';


export {
  THROW_DICE_END,
  THROW_DICE_START,
  RESET_DICE,
  ADD_REMOVE_COUNTERS,
  ADD_ALL_COUNTERS,
  TOGGLE_PLAYERS_TURN,
  PLAYER_GETS_TOKEN_HOME,
  PLAYER_HAS_TOKEN_RESET,
  UPDATE_COUNTER,
  CLICKED_ON_COUNTER_ATTEMPT,
  CLICKED_ON_COUNTER_SUCCESS,
  CLICKED_ON_COUNTER_FAILURE,
  CAN_CLICK_ON_COUNTER,
  HOVERED_ON_COUNTER,
  COUNTER_MOVE_ATTEMPT,
  COUNTER_MOVE_SUCCESS,
  COUNTER_MOVE_FAILURE,
  GAME_START,
  GAME_END,
  LANDED_ON_ROSETTE,
  END_OF_TURN,
  START_OF_TURN,
  SHOW_GAME_MESSAGE,
  HIDE_GAME_MESSAGE,
};

