// @flow

const THROW_DICE_END = 'THROW_DICE_END';
const THROW_DICE_START = 'THROW_DICE_START';

const UPDATE_BOARD = 'UPDATE_BOARD';

const TOGGLE_PLAYERS_TURN = 'TOGGLE_PLAYERS_TURN';
const PLAYER_GETS_TOKEN_HOME = 'PLAYER_GETS_TOKEN_HOME';
const PLAYER_HAS_TOKEN_RESET = 'PLAYER_HAS_TOKEN_RESET';

const MOVE_PIECE = 'MOVE_PIECE';

export {
  THROW_DICE_END,
  THROW_DICE_START,
  UPDATE_BOARD,
  TOGGLE_PLAYERS_TURN,
  PLAYER_GETS_TOKEN_HOME,
  PLAYER_HAS_TOKEN_RESET,
  MOVE_PIECE,
};

